[2022-05-31 11:05:58] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:192)
[stacktrace]
#0 C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(118): Illuminate\\Log\\LogManager->resolve(NULL)
#1 C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(98): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(568): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(252): Illuminate\\Log\\LogManager->error('mysqli_connect(...', Array)
#4 C:\\laragon\\www\\fleet-manager\\framework\\app\\Exceptions\\Handler.php(33): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(ErrorException))
#5 C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(88): App\\Exceptions\\Handler->report(Object(ErrorException))
#6 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(ErrorException))
#7 {main}
"} 
[2022-05-31 11:05:58] laravel.ERROR: mysqli_connect(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO) {"exception":"[object] (ErrorException(code: 0): mysqli_connect(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO) at C:\\laragon\\www\\fleet-manager\\assets\\push_notification\\push_subscription.php:65)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'mysqli_connect(...', 'C:\\\\laragon\\\\www\\\\...', 65)
#1 C:\\laragon\\www\\fleet-manager\\assets\\push_notification\\push_subscription.php(65): mysqli_connect(NULL, NULL, NULL, NULL)
#2 {main}
"} 
[2022-05-31 11:06:05] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:192)
[stacktrace]
#0 C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(118): Illuminate\\Log\\LogManager->resolve(NULL)
#1 C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(98): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(568): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(252): Illuminate\\Log\\LogManager->error('mysqli_connect(...', Array)
#4 C:\\laragon\\www\\fleet-manager\\framework\\app\\Exceptions\\Handler.php(33): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(ErrorException))
#5 C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(88): App\\Exceptions\\Handler->report(Object(ErrorException))
#6 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(ErrorException))
#7 {main}
"} 
[2022-05-31 11:06:05] laravel.ERROR: mysqli_connect(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO) {"exception":"[object] (ErrorException(code: 0): mysqli_connect(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO) at C:\\laragon\\www\\fleet-manager\\assets\\push_notification\\push_subscription.php:65)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'mysqli_connect(...', 'C:\\\\laragon\\\\www\\\\...', 65)
#1 C:\\laragon\\www\\fleet-manager\\assets\\push_notification\\push_subscription.php(65): mysqli_connect(NULL, NULL, NULL, NULL)
#2 {main}
"} 
[2022-05-31 11:06:25] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:192)
[stacktrace]
#0 C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(118): Illuminate\\Log\\LogManager->resolve(NULL)
#1 C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(98): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(568): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(252): Illuminate\\Log\\LogManager->error('mysqli_connect(...', Array)
#4 C:\\laragon\\www\\fleet-manager\\framework\\app\\Exceptions\\Handler.php(33): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(ErrorException))
#5 C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(88): App\\Exceptions\\Handler->report(Object(ErrorException))
#6 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(ErrorException))
#7 {main}
"} 
[2022-05-31 11:06:25] laravel.ERROR: mysqli_connect(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO) {"exception":"[object] (ErrorException(code: 0): mysqli_connect(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO) at C:\\laragon\\www\\fleet-manager\\assets\\push_notification\\push_subscription.php:65)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'mysqli_connect(...', 'C:\\\\laragon\\\\www\\\\...', 65)
#1 C:\\laragon\\www\\fleet-manager\\assets\\push_notification\\push_subscription.php(65): mysqli_connect(NULL, NULL, NULL, NULL)
#2 {main}
"} 
[2022-05-31 16:23:38] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:192)
[stacktrace]
#0 C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(118): Illuminate\\Log\\LogManager->resolve(NULL)
#1 C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(98): Illuminate\\Log\\LogManager->get(NULL)
#2 C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(568): Illuminate\\Log\\LogManager->driver()
#3 C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(252): Illuminate\\Log\\LogManager->error('mysqli_connect(...', Array)
#4 C:\\laragon\\www\\fleet-manager\\framework\\app\\Exceptions\\Handler.php(33): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(ErrorException))
#5 C:\\laragon\\www\\fleet-manager\\framework\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(88): App\\Exceptions\\Handler->report(Object(ErrorException))
#6 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(ErrorException))
#7 {main}
"} 
[2022-05-31 16:23:38] laravel.ERROR: mysqli_connect(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO) {"exception":"[object] (ErrorException(code: 0): mysqli_connect(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO) at C:\\laragon\\www\\fleet-manager\\assets\\push_notification\\push_subscription.php:65)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'mysqli_connect(...', 'C:\\\\laragon\\\\www\\\\...', 65)
#1 C:\\laragon\\www\\fleet-manager\\assets\\push_notification\\push_subscription.php(65): mysqli_connect(NULL, NULL, NULL, NULL)
#2 {main}
"} 
